ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('users.urls', namespace='users')),
    path('', include('sellers.urls', namespace='sellers'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path 
from .views import (
    home_view,
    product_list_view,
    product_detail_view,
    product_create_view,
    write_product_review_view,
    product_search_view,
    add_to_basket_view,
    basket_view,
    update_basket_view,
    customer_address_view,
    checkout_summary_view,
    checkout_view,
    create_checkout_session_view,
    payment_cancel_view,
    payment_success_view,
    stripe_webhook,
    order_history_view,
    email_receipt_view,
    deals_and_sales_view,
)


app_name = 'products'



urlpatterns = [
    path('', home_view, name='product-home'),
    path('products/', product_list_view, name='product-list'),
    path('product/create/', product_create_view, name='product-create'),
    path('product/<uuid:id>/detail/', product_detail_view, name='product-detail'),
    path('product/<uuid:id>/review/',write_product_review_view, name='product-review' ),
    path('product/search/', product_search_view, name='product-search'),
    path('product/deals/sales/', deals_and_sales_view, name='deals-and-sales'),
    path('product/<uuid:id>/add-to-basket/', add_to_basket_view, name='add-to-basket'),
    path('my/basket/', basket_view, name='product-basket'),
    path('update/<str:id>/qty', update_basket_view, name='update-basket'),
    path('shipping/address/', customer_address_view, name='shipping-address'),
    path('checkout/summary/', checkout_summary_view, name='checkout-summary'),
    path('checkout/', checkout_view, name='checkout'),
    path('create/checkout/session/<uuid:id>/', create_checkout_session_view, name='checkout-session'),
    path('payment/success/<uuid:id>/', payment_success_view, name='payment-success'),
    path('payment/cancel/', payment_cancel_view, name='payment-cancel'),
    path('stripe/webhook/', stripe_webhook, name='stripe-webhook'),
    path('order/history/', order_history_view, name='order-history'),
    path('email/receipt/<uuid:id>/', email_receipt_view, name='email-receipt'),
]

users/urls.py
from django.urls import path 
from .views import (
    user_register_view, 
    user_login_view,
    user_logout_view,
    user_profile_view,
    message_view
)


app_name = 'users'


urlpatterns = [
    path('register/', user_register_view, name='user-register'),
    path('login/', user_login_view, name='user-login'),
    path('logout/', user_logout_view, name='user-logout'),
    path('user/profile/', user_profile_view, name='user-profile'),
    path('message/', message_view, name='user-message')
]

products/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
import uuid
from decimal import Decimal
from django.utils import timezone


class ProductCategory(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to='category_images')

    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['name']
        verbose_name_plural = 'Product Categories'


class ProductSubCategory(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE, null=True, blank=True)
    name = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'Product Sub-categories'
        ordering = ['category']


class Product(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    sub_category = models.ForeignKey(ProductSubCategory, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    brand = models.CharField(max_length=50)
    seller_organization = models.CharField(max_length=50)
    product_image = models.ImageField(upload_to='product_image')
    description = models.CharField(max_length=100)
    detail = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    price_str_format = models.CharField(max_length=1000, null=True, blank=True)
    discount_price_str_format = models.CharField(max_length=1000, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    available = models.BooleanField(default=True)
    num_of_times_solid = models.IntegerField(default=0)
    likes = models.DecimalField(max_digits=5, decimal_places=1 ,default=0.0)

    def __str__(self):
        return self.name
    
    def save(self, *arg, **kwarg):
        price = str(self.price)
        self.price_str_format = f'{price[0:-6]},{price[-6:]}'
        super().save(*arg, **kwarg)

    def get_product_image_url(self):
        return self.product_image.url
    
    def get_absolute_url(self):
        return reverse('products:product-detail', args=[str(self.id)])
    
    def get_discount_price(self):
        sub_cat = ['High-end', 'Entry-level']
        item = Product.objects.get(id=self.id)
        if item.sub_category:
            if item.sub_category.name in sub_cat:
                discount = round(item.price - (item.price * Decimal(.10)), 2)
                for char in str(discount):
                    if char == '.':
                        index = str(discount).index(char)
                        discount = f'{str(discount)[0 : index - 3]},{str(discount)[index - 3 : index  + 3]} '
                self.discount_price_str_format = discount
                return discount
        # return 0
    
    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Products'


class ProductImage(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product_images')

    def __str__(self):
        return f'{self.product}'

    class Meta:
        verbose_name_plural = 'Product Images'


class ProductReview(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.TextField()
    rating = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.product.name
    
    def calculate_rating(self):
        reviews = ProductReview.objects.filter(product__id = self.product.id)
        total_reviews = reviews.count()
        added_review = sum([review.rating for review in reviews])
        rating_average = (added_review / ( total_reviews * 5)) * 5
        # self.product.likes = rating_average
        return rating_average
    
    class Meta:
        ordering = ['-created']
        verbose_name_plural = 'Product Reviews'


class Order(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    ordered_date = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    open = models.BooleanField(default=True)

    def get_order_total(self):
        if self.product.get_discount_price():
            order_total = round(self.quantity * Decimal(self.product.get_discount_price().replace(',', '')), 2)
            return order_total
        else:
            order_total = round(self.quantity * self.product.price, 2)
            return order_total
    
    def __str__(self):
        return f'{self.customer.username} - {self.product.name}'
    
    class Meta:
        ordering = ['-open']
    

class Checkout(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    order = models.ManyToManyField(Order)
    date_created = models.DateTimeField(auto_now_add=True)
    checkout_date = models.DateTimeField(null=True)
    total_amount_due = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)
    open = models.BooleanField(default=True)

    def set_amount_due(self):
        customer = User.objects.get(username=self.customer.username)
        checkout = Checkout.objects.get(customer=customer, open=True)
        amount_due = [product.get_order_total() for product in checkout.order.all()]
        self.total_amount_due = round(sum(amount_due), 2)
        checkout.save()
        return round(sum(amount_due), 2)
    
    def __str__(self):
        return f'{self.customer.username} - {self.order}'
    
    class Meta:
        ordering = ['-open']


class ShippingAddress(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    customer = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length= 100)
    email = models.EmailField(max_length=100)
    phone_number = models.IntegerField()
    address = models.CharField(max_length=1000)
    city = models.CharField(max_length=100)
    province = models.CharField(max_length=100, null=True, blank=True)
    state = models.CharField(max_length=100, null=True, blank=True)
    zip_code = models.IntegerField()

    def __str__(self):
        return f'{self.customer.username}'
    
    class Meta:
        verbose_name_plural = 'Addresses'


class CheckoutReceipt(models.Model):
    id = models.UUIDField(
        primary_key=True,
        default=uuid.uuid4,
        editable=False
    )
    checkout = models.ForeignKey(Checkout, on_delete=models.PROTECT)
    customer = models.ForeignKey(User, on_delete=models.PROTECT)
    created = models.DateTimeField(auto_now_add=True)
    receipt_sent_date = models.DateTimeField(null=True)
    sent = models.BooleanField(default=False)
    saving = models.CharField(max_length=100, blank=True, null=True)
    sub_total = models.CharField(max_length=100, null=True, blank=True)
    tax = models.CharField(max_length=100, null=True, blank=True)
    total = models.CharField(max_length=100, null=True, blank=True)
    checkout_summary = models.FileField(upload_to='checkout_summary', null=True, blank=True)



    def __str__(self):
        return self.customer.username
    
    class Meta:
        ordering = ['-receipt_sent_date']
        verbose_name_plural = 'Checkout Receipts'

products/forms.py
from .models import Product, ProductImage, ProductReview, ShippingAddress
from django.forms import ClearableFileInput
from django import forms 




class CreateProductForm(forms.ModelForm):
    class Meta:
        model = Product 
        fields = [
            'category',
            'sub_category',
            'name',
            'brand',
            'seller_organization',
            'product_image',
            'description', 
            'detail', 
            'price', 
            'available'
        ]


class CreateProductImageForm(forms.ModelForm):
    allow_multiple_selected = True
    class Meta:
        model = ProductImage
        fields = ['image']
        labels = {
            'image': 'Additional Product Images'
        }
        widgets = {
            'image': ClearableFileInput(attrs={'multiple': True}),
        }


class ProductReviewForm(forms.Form):
    rating = forms.CharField(max_length=5)
    title = forms.CharField(max_length=100)
    content = forms.CharField(widget=forms.Textarea, required=False)


class ShippingAddressForm(forms.ModelForm):
    class Meta:
        model = ShippingAddress
        fields = [
            'first_name', 
            'last_name', 
            'email', 
            'phone_number', 
            'address', 
            'city', 
            'province',
            'state',
            'zip_code'
        ]

templates/products/checkout_summary.html
{% extends 'index.html' %}
{% load static %}

{% block title %}
    Payment center
{% endblock title %}


{% block content %}

    <div class="payment-center-wrapper">
        <!-- Cart is empty -->
        {% if not query_set %}
            <div class="no-order-history-contents">
                <div class="order-history-nav-bar" style="justify-content: center;">
                    {% with request.resolver_match.url_name as url_name %}
                        <a class="{% if url_name == 'product-basket' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:product-basket' %}">Basket</a>
                        <a class="{% if url_name == 'shipping-address' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:shipping-address' %}">Address</a>
                        <a class="{% if url_name == 'checkout-summary' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:checkout-summary' %}">Checkout</a>
                        <a class="{% if url_name == 'order-history' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:order-history' %}">Order History</a>
                        <a class="{% if url_name == 'user-profile' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'users:user-profile' %}">Profile</a>
                    {% endwith %}
                </div>
                <div class="no-order-history-content">
                    <h3 class="no-order-history-text">Nothing to see here!</h3>
                    <a class="no-order-history-continue-shopping" href="{% url 'products:product-list' %}">Continue Shopping</a>
                </div>
            </div>
        {% else %}
        <!-- End cart is empty -->
            <div class="payment-center-contents">
                <div class="product-basket-nav-bar">
                    {% with request.resolver_match.url_name as url_name %}
                        <a class="{% if url_name == 'product-basket' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:product-basket' %}">Basket</a>
                        <a class="{% if url_name == 'shipping-address' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:shipping-address' %}">Address</a>
                        <a class="{% if url_name == 'checkout-summary' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:checkout-summary' %}">Checkout</a>
                        <a class="{% if url_name == 'order-history' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'products:order-history' %}">Order History</a>
                        <a class="{% if url_name == 'user-profile' %}active-product-basket-nav-link{% else %}product-basket-nav-link{% endif %}" href="{% url 'users:user-profile' %}">Profile</a>
                    {% endwith %}
                </div>
                <!-- For large screen -->
                <div class="purchase-items">
                    <div class="purchased-item-headers">
                        <h4>Name</h4>
                        <h4>Price</h4>
                        <h4>Quantity</h4>
                        <h4>Total</h4>
                    </div>
                    {% for item in query_set %}
                        <a class="purchase-item" href="{{ item.product.get_absolute_url }}">
                            <p>{{ item.product.name }}</p>
                            {% if item.product.get_discount_price %}
                                <p>P{{ item.product.discount_price_str_format }}</p>
                                <!-- from Product model method -->
                            {% else %}
                                <p>P{{ item.product.price_str_format }}</p>
                            {% endif %}
                            <p>{{ item.quantity }}</p>
                            {% for order in order_total %}
                                {% if item.product.id == order.id%}
                                    <p>P{{ order.order_total }}</p>
                                {% endif %}
                            {% endfor %}
                            <!-- from Order model method -->
                        </a>
                    {% endfor %}
                </div>

                <!-- For mobile screen -->
                <div class="sm-purchase-items">
                    {% for item in query_set %}
                        <a href="{{ item.product.get_absolute_url }}" class="sm-purchase-item">
                            <div class="sm-purchased">
                                <h4>Order</h4>
                                <p>{{ forloop.counter }}</p>
                            </div>
                            <div class="sm-purchased">
                                <h4>Name</h4>
                                <p>{{ item.product.name }}</p>
                            </div>
                            <div class="sm-purchased">
                                <h4>Price</h4>
                                {% if item.product.get_discount_price %}
                                    <p>P{{ item.product.discount_price_str_format }}</p>
                                    <!-- from Product model method -->
                                {% else %}
                                    <p>P{{ item.product.price_str_format }}</p>
                                {% endif %}
                            </div>
                            <div class="sm-purchased">
                                <h4>Quantity</h4>
                                <p>{{ item.quantity }}</p>
                            </div>
                            <div class="sm-purchased">
                                <h4>Total</h4>
                                {% for order in order_total %}
                                    {% if item.product.id == order.id%}
                                        <p>P{{ order.order_total }}</p>
                                    {% endif %}
                                {% endfor %}
                            </div>
                        </a>
                    {% endfor %}
                </div>

                <div class="purchase-items-total-amount-container">
                    <div class="purchase-item-total-amount-content">
                        <h2 class="purchase-item-total-amount-header-text">Amount Due</h2>
                        <div class="purchase-item-total-amount-header">
                            <h4>Quantity</h4>
                            <p>{{ num_of_product }}</p>
                        </div>
                        <div class="purchase-item-total-amount-header">
                            <h4>Savings</h4>
                            {% if discount_amount %}
                                <p>P{{ discount_amount }}</p>
                            {% else %}
                                <p>n/a</p>
                            {% endif %}
                        </div>
                        <div class="purchase-item-total-amount-header">
                            <h4>Sub-total</h4>
                            <p>P{{ sub_total }}</p>
                        </div>
                        <div class="purchase-item-total-amount-header">
                            <h4>VAT</h4>
                            <p>P{{ vat }}</p>
                        </div>
                        <div class="purchase-item-total-amount-header">
                            <h4>Total</h4>
                            <p>P{{ total }}</p>
                        </div>
                        <!-- coming from context_processor get_basket_total() -->

                        <form class="checkout-form" action="{% url 'products:checkout' %}" method="POST">
                            {% csrf_token %}
                            <button class="purchase-btn" type="submit" id="checkout-button">Purchase</button>
                            <a href="{% url 'products:product-list' %}" class="checkout-form-continue-shopping-btn">Continue Shopping</a>
                        </form>
                    </div>
                </div>
            </div>
        {% endif %}
    </div>
    
    <script>

        const user = '{{ request.user.shippingaddress_set.all.first.id }}'
        const address_url = '{% url "products:shipping-address" %}'
        
        console.log(address_url)
        
    </script>

{% endblock content %}

templates/products/download_receipt.html
<h1>DOWNLOAD RECEIPT</h1>

templates/products/home.html
{% extends 'index.html' %}



{% block title %}
    Home
{% endblock title %}



{% block content %}

    <div class="categories-wrapper">
        <div class="categories-contents">
            <div class="categories-header-container">
                <h2 class="categories-header">Categories</h2>
                <p>
                    It is a long established fact that a reader will be distracted 
                    by the readable content of a page when looking at its layout.
                </p>
            </div>
            <div class="categories">
                {% for cat in category %}
                <a href="{% url 'products:deals-and-sales' %}?str=category {{ cat.name }}" class="category">
                    <h3 class="category-name">{{ cat.name }}</h3>
                    <div class="category-img">
                        <img class="img" src="{{ cat.image.url }}" alt="">
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock content %}

templates/products/payment_cancel.html
{% extends 'index.html' %}


{% block title %}
    Cancel payment
{% endblock title %}


{% block content %}

    <div class="cancel-payment-wrapper">
        <h1>Payment has been canceled</h1>
    </div>

{% endblock content %}

templates/products/product_create.html
{% extends 'index.html' %}



{% block title %}
    Create
{% endblock title %}

 
{% block content %}

    <div class="product-create-form-wrapper">
        <div class="product-create-form-contents">
            <h2 class="create-your-product-header">Please Add Your Product</h2>
            <form class="create-form" action="{% url 'products:product-create' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="product-create-input-container">
                    <div class="product-category-input">
                        {{ product_form.category.label_tag}}
                        <p>{{ product_form.category }}</p>
                    </div>
                    <div class="product-sub-category-input">
                        {{ product_form.sub_category.label_tag}}
                        <p id="sub-category">{{ product_form.sub_category }}</p>
                    </div>
                    <div class="product-name-input">
                        {{ product_form.name.label_tag}}
                        <p>{{ product_form.name }}</p>
                    </div>
                    <div class="product-brand-input">
                        {{ product_form.brand.label_tag}}
                        <p>{{ product_form.brand }}</p>
                    </div>
                    <div class="product-seller-organization-input">
                        {{ product_form.seller_organization.label_tag}}
                        <p>{{ product_form.seller_organization }}</p>
                    </div>
                    <div class="product-image-input">
                        {{ product_form.product_image.label_tag}}
                        <p>{{ product_form.product_image }}</p>
                    </div>
                    <div class="product-price-input">
                        {{ product_form.price.label_tag}}
                        <p>{{ product_form.price }}</p>
                    </div>
                    <div class="product-available-input">
                        {{ product_form.available.label_tag}}
                        {{ product_form.available }}
                    </div>
                </div>
                <div class="product-create-input-container">
                    <div class="product-image-input">
                        {{ image_form.image.label_tag }}
                        <p>{{ image_form.image }}</p>
                        <ul class="image-upload-warning">
                            <li>maxium & minium 3 images.</li>
                        </ul>
                    </div>
                    <div class="product-description-input">
                        {{ product_form.description.label_tag}}
                        <p>{{ product_form.description}}</p>
                        <ul class="image-upload-warning">
                            <li>maxium characters 50.</li>
                        </ul>
                    </div>
                    <div class="product-detail-textarea">
                        {{ product_form.detail.label_tag}}
                        <p>{{ product_form.detail}}</p>
                    </div>
                    <div class="create-form-btns">
                        <button type="submit">Add Product</button>
                        <a href="{% url 'products:product-list' %}">Cancel</a>
                    </div>
                </div>
            </form>
        </div>
    </div>

    <script>

        const productSubCategoryInput = document.querySelector('.product-sub-category-input')
        const subCategories = '{{ sub_categories|safe }}'
        const json_obj = JSON.parse(subCategories)
        
        const idCategory = document.querySelector('#id_category')
        const idSubCategory = document.querySelector('#id_sub_category')
        const select = ''

        productSubCategoryInput.style.display = 'none'

        idCategory.addEventListener('click', (e) => {
            const id = e.currentTarget.value
            json_obj.map((obj) => {
                if(obj.id === parseInt(id)) {
                    productSubCategoryInput.style.display = 'flex'
                    const subCats = obj.sub_categories
                    const data = subCats.map((subCat) => {
                        return(
                            `<option value=${subCat.id}>${subCat.name}</option>`
                        )
                    })

                    data.splice(0, 0, '<option value="" selected="">---------</option>')
                    idSubCategory.innerHTML = data.join(' ')
                }
                else {
                    const new_obj = json_obj.find((obj) => {
                        if(obj.id === parseInt(id)) {
                            return obj
                        }
                    })
                    if(!new_obj) {
                        productSubCategoryInput.style.display = 'none'
                    }
                }
            })
        })
    

        const idName = document.querySelector('#id_name')
        idName.placeholder = 'Product name'

        const idBrand = document.querySelector('#id_brand')
        idBrand.placeholder = 'Brand name'

        const idSellerOrganization = document.querySelector('#id_seller_organization')
        idSellerOrganization.placeholder = 'Your organization'

        const idPrice = document.querySelector('#id_price')
        idPrice.placeholder = 'P0.00'

        const idDescription = document.querySelector('#id_description')
        idDescription.placeholder = 'Description'

        const idDetail = document.querySelector('#id_detail')
        idDetail.placeholder = 'Product detail'

    </script>

{% endblock content %}

{% block scrollbar %}
{% endblock scrollbar %}