ecommerce_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products')),
    path('', include('users.urls', namespace='users')),
    path('', include('sellers.urls', namespace='sellers'))
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path 
from .views import (
    home_view,
    product_list_view,
    product_detail_view,
    product_create_view,
    write_product_review_view,
    product_search_view,
    add_to_basket_view,
    basket_view,
    update_basket_view,
    customer_address_view,
    checkout_summary_view,
    checkout_view,
    create_checkout_session_view,
    payment_cancel_view,
    payment_success_view,
    stripe_webhook,
    order_history_view,
    email_receipt_view,
    deals_and_sales_view,
)


app_name = 'products'



urlpatterns = [
    path('', home_view, name='product-home'),
    path('products/', product_list_view, name='product-list'),
    path('product/create/', product_create_view, name='product-create'),
    path('product/<uuid:id>/detail/', product_detail_view, name='product-detail'),
    path('product/<uuid:id>/review/',write_product_review_view, name='product-review' ),
    path('product/search/', product_search_view, name='product-search'),
    path('product/deals/sales/', deals_and_sales_view, name='deals-and-sales'),
    path('product/<uuid:id>/add-to-basket/', add_to_basket_view, name='add-to-basket'),
    path('my/basket/', basket_view, name='product-basket'),
    path('update/<str:id>/qty', update_basket_view, name='update-basket'),
    path('shipping/address/', customer_address_view, name='shipping-address'),
    path('checkout/summary/', checkout_summary_view, name='checkout-summary'),
    path('checkout/', checkout_view, name='checkout'),
    path('create/checkout/session/<uuid:id>/', create_checkout_session_view, name='checkout-session'),
    path('payment/success/<uuid:id>/', payment_success_view, name='payment-success'),
    path('payment/cancel/', payment_cancel_view, name='payment-cancel'),
    path('stripe/webhook/', stripe_webhook, name='stripe-webhook'),
    path('order/history/', order_history_view, name='order-history'),
    path('email/receipt/<uuid:id>/', email_receipt_view, name='email-receipt'),
]

sellers/urls.py
from django.urls import path 
from .views import seller_register_view


app_name = 'sellers'



urlpatterns = [
    path('seller/register/', seller_register_view, name='seller-register')
]

users/urls.py
from django.urls import path 
from .views import (
    user_register_view, 
    user_login_view,
    user_logout_view,
    user_profile_view,
    message_view
)


app_name = 'users'


urlpatterns = [
    path('register/', user_register_view, name='user-register'),
    path('login/', user_login_view, name='user-login'),
    path('logout/', user_logout_view, name='user-logout'),
    path('user/profile/', user_profile_view, name='user-profile'),
    path('message/', message_view, name='user-message')
]

templates/banner.html
{% load static %}



<div class="large-screen-banner-wrapper">
    <div class="banner-img-container">
        <img class="large-img" src="{% static 'images/laptop.webp' %}" alt="">
        <img class="small-img" src="{% static 'images/laptop-small.webp' %}" alt="">
        <img class="mobile-img" src="{% static 'images/laptop-mobile.webp' %}" alt="">
        <div class="banner-img-background-overlay">
            <div class="img-banner-content-container">
                <div class="img-banner-text">
                    <h1 class="img-banner-h1-header">Up to 10% Off On Laptop!</h1>
                    <p class="img-banner-paragraph">
                        this a long established fact that a reader 
                        will be distracted by the readable content of
                        a page when looking at its layout.
                    </p>
                    <a href="{% url 'products:deals-and-sales' %}?str=up to 10% off laptop" class="more-info">More Info</a>
                </div>
            </div>
        </div>
    </div>
    <div class="banner-img-container">
        <img class="large-img" src="{% static 'images/pc.webp' %}" alt="">
        <img class="small-img" src="{% static 'images/pc-small.webp' %}" alt="">
        <img class="mobile-img" src="{% static 'images/pc-mobile.webp' %}" alt="">
        <div class="banner-img-background-overlay">
            <div class="img-banner-content-container">
                <div class="img-banner-text">
                    <h1 class="img-banner-h1-header">Up to 10% Off On Desktop PC!</h1>
                    <p class="img-banner-paragraph">
                        this a long established fact that a reader 
                        will be distracted by the readable content of
                        a page when looking at its layout.
                    </p>
                    <a href="{% url 'products:deals-and-sales' %}?str=up to 10% off desktop pc" class="more-info">More Info</a>
                </div>
            </div>
        </div>
    </div>
    <div class="banner-img-container">
        <img class="large-img" src="{% static 'images/accessories.webp' %}" alt="">
        <img class="small-img" src="{% static 'images/accessories-small.webp' %}" alt="">
        <img class="mobile-img" src="{% static 'images/accessories-mobile.webp' %}" alt="">
        <div class="banner-img-background-overlay">
            <div class="banner-img-background-overlay">
                <div class="img-banner-content-container">
                    <div class="img-banner-text">
                        <h1 class="img-banner-h1-header">Up to 30% Off On Accessories!</h1>
                        <p class="img-banner-paragraph">
                            this a long established fact that a reader 
                            will be distracted by the readable content of
                            a page when looking at its layout.
                        </p>
                        <a href="{% url 'products:deals-and-sales' %}?str=up to 30% off accessories" class="more-info">More Info</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="banner-arrow-left translate-btn">
        <span class="material-symbols-outlined">keyboard_arrow_left</span>
    </div>
    <div class="banner-arrow-right translate-btn">
        <span class="material-symbols-outlined">keyboard_arrow_right</span>
    </div>
</div>

 

templates/footer.html
<footer id="footer">
    <div class="footer-wrapper1">
        <div class="footer-contents">
            <div class="footer-content">
                <div class="footer-header-text-container">
                    <h2 class="footer-content-header-text">About</h2>
                    <div class="footer-header-text-underline"></div>
                </div>
                <div class="about-content-container">
                    <a class="about-brand-name" href="{% url 'products:product-home' %}">
                        <!-- <h1>AiAi Market</h1> -->
                        <h1>aiai<span>e-market</span></h1>
                        <!-- <p>THE PLACE TO SHOP</p> -->
                    </a>
                    <p class="footer-about-us-text">
                        There are many variations of passages of Lorem Ipsum available, 
                        but the majority have suffered alteration in some form, by 
                        injected humour, or randomised words which don't look even slightly 
                        believable. If you are going to use a passage of Lorem Ipsum.
                    </p>
                </div>
            </div>
            <div class="footer-content">
                <div class="footer-header-text-container">
                    <h2 class="footer-content-header-text">Quick Links</h2>
                    <div class="footer-header-text-underline"></div>
                </div>
                
                <nav class="footer-nav-links">
                    <a class="footer-nav-link" href="{% url 'products:product-home' %}">Home</a>
                    <a class="footer-nav-link" href="{% url 'products:product-list' %}">Products</a>
                    {% if request.user.is_authenticated %}
                        <a class="footer-nav-link" href="{% url 'products:product-basket' %}">Basket</a>
                        <a class="footer-nav-link" href="{% url 'products:product-create' %}">Create</a>
                        <a class="footer-nav-link" href="{% url 'users:user-profile' %}">Profile</a>
                        <a class="footer-nav-link" href="{% url 'sellers:seller-register' %}">Sell on AiAi Market</a>
                        <a class="footer-nav-link" href="{% url 'users:user-logout' %}">Logout</a>
                    {% else %}
                        <a class="footer-nav-link" href="{% url 'users:user-register' %}">Register</a>
                        <a class="footer-nav-link" href="{% url 'users:user-login' %}">Login</a>
                    {% endif %}
                </nav>
            </div>
            <div class="footer-content last-element">
                <div class="footer-header-text-container">
                    <h2 class="footer-content-header-text">Contact</h2>
                    <div class="footer-header-text-underline"></div>
                </div>
                
                <div class="footer-messages">
                    <div class="footer-address">
                        <h4>Address</h4>
                        <address style="max-width:200px;margin:0 auto">
                            123 Main st. Baguio City, Benguet PH 2600
                        </address>
                    </div>
                    <div class="footer-phone">
                        <h4>Phone</h4>
                        <a href="tel:+631233456789">+63-123-345-6789</a>
                    </div>
                    <div class="footer-email">
                        <h4>Email</h4>
                        <a href="mailto:aiaimarket@gmail.com">aiaimarket@gmail.com</a>
                    </div>
                </div>
            </div>
            <div class="footer-content">
                <div class="footer-header-text-container">
                    <h2 class="footer-content-header-text">Leave a Message</h2>
                    <div class="footer-header-text-underline"></div>
                </div>
                <form class="message-form" action="{% url 'users:user-message' %}" method="POST">
                    {% csrf_token %}
                    <label for="email">Email</label>
                    <input id="email" name='email' type='email' required>
                    <label for="message">Message</label>
                    <textarea id="message" name="message" id="" cols="30" rows="10" required></textarea>
                    <ul class="message-info">
                        <li>If you are a registered user, please include your username.</li>
                        <li>If you have not registered, please consider registering.</li>
                    </ul>
                    <button type="submit">Submit</button>
                </form>
            </div>
        </div>
    </div>
    <div class="footer-wrapper2">
        <div class="footer-social-links">
            <a class="social-link" href="https://www.twitter.com" target="_blank">
                <i class="fa-brands fa-twitter"></i>
            </a>
            <a class="social-link" href="https://www.youtube.com" target="_blank">
                <i class="fa-brands fa-youtube"></i>
            </a>
            <a class="social-link" href="https://www.instagram.com" target="_blank">
                <i class="fa-brands fa-instagram"></i>
            </a>
            <a class="social-link" href="https://www.facebook.com" target="_blank">
                <i class="fa-brands fa-square-facebook"></i>
            </a>
        </div>
        <div class="copy-right">
            <p class="copy-right-text">&copyCopyright 2023 AiAi Market. All Rights Reserved.</p>
        </div>
    </div>
</footer>

<script>
    const messageBox = document.querySelector('#message')
    const email = document.querySelector('#email')
    const messageInfo = document.querySelector('.message-info')

    function handleEvent(e) {
        if(e.target == messageBox) {
            messageInfo.style.display = 'grid'
        }else if(e.target == email) {
            messageInfo.style.display = 'none'
        }
    }

    messageBox.addEventListener('click', handleEvent)
    email.addEventListener('click', handleEvent)

</script>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="shop, online market, gadgets, PC, laptop">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,300,400,500,700,900&display=swap">
    <link href="https://fonts.googleapis.com/css2?family=Lobster&display=swap" rel="stylesheet">

    <!-- google material icon -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

    <!-- Font awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

   <!-- local css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/products.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/users.css' %}">

    <title>{% block title %}{% endblock title %}</title>

</head>
<body id="body">
    
        {% block navbar %}
            <header id="header">
                {% include 'navbar.html' %}
            </header>
        {% endblock navbar%}
   
    <main>
        <div class="main-banner">
            {% block banner %}
                {% include 'banner.html' %}
            {% endblock banner %}
        </div>

        <div class="main-content">
            {% include 'messages.html' %}
            
            {% block content %}
            {% endblock content %}
        
            {% block scrollbar %}
                <div class="scroll-btns">
                    <a href="#header" class="scroll-up">
                        <span class="material-symbols-outlined">keyboard_arrow_up</span>
                    </a>
                    <a href="#footer" class="scroll-down">
                        <span class="material-symbols-outlined">keyboard_arrow_down</span>
                    </a>
                </div>
            {% endblock scrollbar %}
        </div>
    </main>

    {% block footer %}
        {% include 'footer.html' %}
    {% endblock footer %}
    <script src="{% static 'js/main.js' %}"></script>
</body>
</html>

templates/messages.html
<style>

@keyframes drop_message {
        from {
            top: -100%
        }
        to {
            top: 25%
        }
    }

    .message-container {
        position: absolute;
        z-index: 300;
        left: 50%;
        transform: translateX(-50%);
        padding: 1rem;
        animation-name: drop_message;
        animation-duration: 800ms;
        animation-direction: normal;
        animation-fill-mode: forwards;
        border-radius: 10px;
        width: 95%;
        max-width: 700px;
    }

    .success {
        color: #000000;
        background: #5FD87B;
    }

    .warning {
        color: #000000;
        background: #FFD557;
    }

    .error {
        color: #000000;
        background: #ff7e8d;
    }

    .info {
        color: #000000;
        background: #1CB3CA;
    }

    .message {
        letter-spacing: 0.05rem;
        display: flex;
        align-items: center;
        justify-content: space-between;
        gap: 1.5rem;
        font-size: 1rem;
        font-weight: 700;
        line-height: 1.3;
    }

    .close-message-btn {
        cursor: pointer;
        border-radius: 50%;
        background: var(--black-95);
        width: 33px;
        aspect-ratio: 1/1;
        display: flex;
        align-items: center;
        justify-content: center;
    }

</style>


<!-- <div class="success message-container">
    <p class="message">Lorem Ipsum is simply dummy text of the printing and typesetting
        <span class="material-symbols-outlined close-message-btn">close</span>
    </p>
</div> -->

{% if messages %}
    {% for message in messages%}
        {% if message.tags == 'success' %}
            <div class="success message-container">
                <p class="message">{{ message }}
                    <span class="material-symbols-outlined close-message-btn">close</span>
                </p>
            </div>
        {% elif message.tags == 'error' %}
            <div class="error message-container">
                <p class="message">{{ message }}
                    <span class="material-symbols-outlined close-message-btn">close</span>
                </p>
            </div>
        {% elif message.tags == 'warning' %}
            <div class="warning message-container">
                <p class="message">{{ message }}
                    <span class="material-symbols-outlined close-message-btn">close</span>
                </p>
            </div>
        {% elif message.tags == 'info' %}
            <div class="info message-container">
                <p class="message">{{ message }}
                    <span class="material-symbols-outlined close-message-btn">close</span>
                </p>
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

<script>
    const closeMessageBtn = [...document.querySelectorAll('.close-message-btn')]
    const messageContainer = [...document.querySelectorAll('.message-container')]

    closeMessageBtn.forEach((btn) => {
        btn.addEventListener('click', (e) => {
            const parent = e.currentTarget.parentElement.parentElement
            parent.style.display = 'none'
        })
    })


    messageContainer.forEach((message) => {
        const timeOutId = setTimeout(() => {
            message.style.display = 'none'
            clearTimeout(timeOutId)
        }, 5000)
    })
    

</script>

templates/navbar.html
<div class="nav-bar-wrapper">
    <a class="brand-name" href="{% url 'products:product-home' %}">
        <h1>aiai<span>e-market</span></h1>
    </a>

    <form class="search-form" action="{% url 'products:product-search' %}" method="GET">
        <input class="search-form-input" type="text", name='q' required placeholder="Search">
        <button class="search-form-submit-btn" type="submit">
            <span class="material-symbols-outlined">search</span>
        </button>
    </form>


    {% with request.resolver_match.url_name as url_name %}
        <nav class="nav-links">
            <a class="nav-link {% if url_name == 'product-list' %}active-nav-link{% endif %}" href="{% url 'products:product-list' %}">Products</a>
            {% if not request.user.is_authenticated %}
                <a class="nav-link {% if url_name == 'user-login' %}active-nav-link{% endif %}" href="{% url 'users:user-login' %}">Login</a>
                <a class="nav-link {% if url_name == 'user-register' %}active-nav-link{% endif %}" href="{% url 'users:user-register' %}">Register</a>
            {% else %}
                <div class="logged-in-user-nav-link-container">
                    <div class="toggle-user-navbar">
                        <img class="logged-in-navbar-user-profile-img" src="{{request.user.userprofile.profile_image.url}}" alt="">
                        <p class="logged-in-navbar-username">{{ request.user.username }}</p>
                        <span class="material-symbols-outlined logged-in-navbar-arrow-down">
                            keyboard_arrow_down
                        </span>
                        <span class="material-symbols-outlined logged-in-navbar-arrow-up">
                            keyboard_arrow_up
                        </span>
                    </div>
                    <div class="logged-in-user-nav-links">
                        <a class="nav-basket {% if url_name == 'product-basket' %}active-nav-link{% endif %}" href="{% url 'products:product-basket' %}">
                            Basket
                            <span class="material-symbols-outlined shopping-cart">shopping_basket</span>
                            <span class="num-of-items">{{ num_of_product }}</span>
                        </a>
                        <a class="nav-link {% if url_name == 'user-profile' %}active-nav-link{% endif %}" href="{% url 'users:user-profile' %}">Profile</a>
                        <a class="nav-link {% if url_name == 'order-history' %}active-nav-link{% endif %}" href="{% url 'products:order-history' %}">Order history</a>
                        {% if request.user.sellersignup %}
                            <a class="nav-link {% if url_name == 'product-create' %}active-nav-link{% endif %}" href="{% url 'products:product-create' %}">Add Product to Sell</a>
                        {% else %}
                            <a class="nav-link {% if url_name == 'seller-signup' %}active-nav-link{% endif %}" href="{% url 'sellers:seller-register' %}">Sell on AiAi Market</a>
                        {% endif %}
                        <a class="nav-link {% if url_name == 'user-logout' %}active-nav-link{% endif %}" href="{% url 'users:user-logout' %}">Logout</a>
                    </div>
                </div>
            {% endif %}
            <button type="button" class="nav-link nav-link-search-button">
                Search
                <span class="material-symbols-outlined search-icon">search</span>
            </button>
        </nav>
    {% endwith %}
</div>

<!-- Mobile screen  -->
<div class="mobile-nav-bar-wrapper">
    <a class="mobile-brand-name" href="{% url 'products:product-home' %}">
        <h1>aiai<span>e-market</span></h1>
    </a>
    <form class="mobile-search-form" action="{% url 'products:product-search' %}" method="GET">
        <input class="mobile-search-form-input" type="text", name='q' required placeholder="Search">
        <button class="mobile-search-form-submit-btn" type="submit">
            <!-- <span class="material-symbols-outlined mobile-form-search-icon">search</span> -->
            <span class="material-symbols-outlined mobile-form-close-icon">close</span>
        </button>
    </form>

    <span class="material-symbols-outlined mobile-search-icon">search</span>

    <div class="mobile-toggle-nav-btn">
        <span class="material-symbols-outlined mobile-menu-btn">menu</span>
    </div>
    {% with request.resolver_match.url_name as url_name %}
        <nav class="mobile-nav-links">
            <span class="material-symbols-outlined mobile-nav-close-btn">close</span>

            {% if request.user.is_authenticated %}
                <a class="mobile-basket-link mobile-nav mobile-nav-link {% if url_name == 'product-basket' %}mobile-active-nav-link{% endif %}" href="{% url 'products:product-basket' %}">
                    Basket
                    <span class="material-symbols-outlined mobile-shopping-cart">shopping_basket</span>
                    <span class="mobile-num-of-items">{{ num_of_product }}</span>
                </a>
            {% endif %}

            <a class="mobile-nav mobile-nav-link {% if url_name == 'product-list' %}mobile-active-nav-link{% endif %}" href="{% url 'products:product-list' %}">Products</a>
            {% if not request.user.is_authenticated %}
                <a class="mobile-nav mobile-nav-link {% if url_name == 'user-login' %}mobile-active-nav-link{% endif %}" href="{% url 'users:user-login' %}">Login</a>
                <a class="mobile-nav mobile-nav-link {% if url_name == 'user-register' %}mobile-active-nav-link{% endif %}" href="{% url 'users:user-register' %}">Register</a>
            {% else %}
                <a class="mobile-nav mobile-nav-link {% if url_name == 'user-profile' %}mobile-active-nav-link{% endif %}" href="{% url 'users:user-profile' %}">Profile</a>
                <a class="mobile-nav mobile-nav-link {% if url_name == 'order-history' %}mobile-active-nav-link{% endif %}" href="{% url 'products:order-history' %}">Order history</a>
                {% if request.user.sellersignup %}
                    <a class="mobile-nav mobile-nav-link {% if url_name == 'product-create' %}mobile-active-nav-link{% endif %}" href="{% url 'products:product-create' %}">Add Product to Sell</a>
                {% else %}
                    <a class="mobile-nav mobile-nav-link {% if url_name == 'seller-signup' %}mobile-active-nav-link{% endif %}" href="{% url 'sellers:seller-register' %}">Sell on AiAi Market</a>
                {% endif %}
                
                <a class="mobile-nav mobile-nav-link {% if url_name == 'user-logout' %}mobile-active-nav-link{% endif %}" href="{% url 'users:user-logout' %}">Logout</a>
            {% endif %}
        </nav>
    {% endwith %}
    <div class="mobile-nav-background-layout"></div>
</div>

<script>

    const mobileSearchForm = document.querySelector('.mobile-search-form')
    const mobileBrandName = document.querySelector('.mobile-brand-name')
    const mobileSearchIcon = document.querySelector('.mobile-search-icon')

    const mobileFormCloseBtn = document.querySelector('.mobile-form-close-icon')


    function mobileSearchFormEvent(e) {
        if(e.target === mobileSearchIcon) {
            mobileSearchForm.style.display = 'flex'
            mobileBrandName.style.display = 'none'
            mobileSearchIcon.style.display = 'none'
            mobileFormCloseBtn.style.display = 'flex'
        }else if(e.target === mobileFormCloseBtn) {
            mobileSearchForm.style.display = 'none'
            mobileBrandName.style.display = 'flex'
            mobileSearchIcon.style.display = 'flex'
            mobileFormCloseBtn.style.display = 'none'
        }
    }

    mobileSearchIcon.addEventListener('click', mobileSearchFormEvent)
    mobileFormCloseBtn.addEventListener('click', mobileSearchFormEvent)

</script>